### ISSUE TITLE
Error occurs by invalid DATE_FORMAT

### ISSUE THREAD

**Issue by tbrand** [crystal-lang/crystal-sqlite3#13]
When I define a time column to my table, I got an error like
```
unexpected char: '.' (19) (Time::Format::Error)
```
When I read it as String, I got a format
```
2016-12-25 14:25:53
```

Is the [DATE_FORMAT](https://github.com/crystal-lang/crystal-sqlite3/blob/0396d637716428c066c9a7b7a413a0b31b635f71/src/sqlite3.cr#L5) right?

I think it should be `"%F %T"`.

My SQLite version is here.
```
3.8.10.2 2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4
```

**Comment by bcardiff** [comment]
It isn't right. @juanedi notice that the NOW() function format should match this constant also so Time crystal type is able to read those value. 

It can't recall where that format came from.

Note that sqlite does not handle strict types so it depends how you insert that "date" into the database how you are going to get it. 

So, for consistency we should store in the same format as NOW() and maybe handle on read different precision for datetimes.

**Comment by tbrand** [comment]
Understood, I used `current_timestamp`.
Will change it to `NOW`:+1:

Thanks for your advice :)

**Comment by bcardiff** [comment]
It still wont work with NOW(). The format doesn't match. If it is blocking a PR is welcome, otherwise during the follow days we will take care of it.

**Comment by juanedi** [comment]
[These](https://www.sqlite.org/lang_datefunc.html) are the functions for time formatting in SQLite.

The closest to what we need is `datetime`, but it doesn't have milliseconds precision :-(

We can always use something like `strftime('%Y-%m-%d %H:%M:%f', 'now')`, but it would be great to settle with one of those named formats to avoid people having to hardcode a format string for `strftime` in their queries.

**Comment by tbrand** [comment]
For my purpose, I decided to store the time as String and parse it when restore it.
Since I have to support many database platforms... :)

**Comment by bcardiff** [comment]
Ok, just reviewed and dump a issue at #14 to track this. The current format is the one with more precision in sqlite, so that is the reason to pick it.
