### ISSUE TITLE
SQLite3::Connection#dump fails to read >1MB files

### ISSUE THREAD

**Issue by hinrik** [crystal-lang/crystal-sqlite3#15]
```crystal
require "sqlite3"

mem_db = DB.open "sqlite3::memory:"
file_db = DB.open "sqlite3:test.sqlite"

mem_db.using_connection do |mem_conn|
  file_db.using_connection do |file_conn|
    file_conn.dump(mem_conn)
  end 
end
```

The above fails with `not an error (SQLite3::Exception)` when the size of `test.sqlite` exceeds 1024K. Works fine if I delete enough rows beforehand and issue `VACUUM` to get the size below 1024K. The issue is the file size, because if I don't do a `VACUUM`, it still fails.

Specifically, on [line 77 in `src/sqlite3/connection.cr`](https://github.com/crystal-lang/crystal-sqlite3/blob/master/src/sqlite3/connection.cr#L77), `code` is `OKAY` when the expected value is `DONE`.

**Comment by bcardiff** [comment]
fixed with #16
