### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal-sqlite3#29]
Hi @bcardiff 

v0.8.2 was released on Mar 21, at least 5 commit and fixes has been published on master.

Would be good to have a new release

Thanks you for maintain this shard! <3

**Comment by bcardiff** [comment]
v0.8.3 released :shipit:

**Comment by faustinoaq** [comment]
Hi @bcardiff , Thank you so much for this release!

WDYT about https://github.com/crystal-lang/crystal-mysql/issues/48 ? 😅

**Comment by bcardiff** [comment]
Done ;-) it took a little longer the release of mysql.
