### ISSUE TITLE
Fail With Debian Testing

### ISSUE THREAD

**Issue by tigernassau** [crystal-lang/crystal-sqlite3#35]
Debian Testing
Crystal 25.1
SQLITE3 installed

shards install seemed to work ok

require "kemal"
require "db"
require "sqlite3"
DB.open "sqlite3://ourwebsite.db" do |db|

/usr/bin/ld: cannot find -lsqlite3 (this usually means you need to install the development package for libsqlite3)
/usr/bin/ld: cannot find -lz (this usually means you need to install the development package for libz)
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/work/.cache/crystal/crystal-run-website.tmp'  -rdynamic  -lsqlite3 -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

we have tried to look for a zlib-dev but cannot find.  We have this working on a Fedora 28 machine so something is missing with packages 
appreciate any help

**Comment by RX14** [comment]
it looks to be `zlib1g-dev` and `libsqlite3-dev`

**Comment by Qu4tro** [comment]
I've ran into this building a docker image with alpine. Just leaving here the packages needed for a static release with a app with a sqlite3 dependency:
`RUN apk add -u sqlite-static sqlite-dev`
