### ISSUE TITLE
Unhandled exception when writing to DB

### ISSUE THREAD

**Issue by mhusmann** [crystal-lang/crystal-sqlite3#46]
```
def write_entry
      args = [] of DB::Any
      args << @id
      args << @datum
      args << @ht
      args << @nt
      args << @tarif_id
      MY_DB.exec "INSERT INTO dayly VALUES(?, ?, ?, ?, ?)", args
end
```

When writing to the database I get the following exception:

Unhandled exception: SQLite3::Statement does not support Array(Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil) params (Exception)

It worked fine with previous releases

**Comment by bcardiff** [comment]
As of crystal-db 0.7.0, for a dynamic list of arguments you should use.

```crystal
MY_DB.exec "INSERT INTO dayly VALUES(?, ?, ?, ?, ?)", args: args
```

Some drivers allow arrays as arguments and it was an ambiguous API. 
More info at https://crystal-lang.org/2019/09/23/crystal-0.31.0-released.html#crystal-db-070

**Comment by mhusmann** [comment]
Thanks, Brian

that works.

Kind regards
Michael

Am Di., 24. Sept. 2019 um 15:34 Uhr schrieb Brian J. Cardiff <
notifications@github.com>:
