### ISSUE TITLE
[FEATURE] Connection param for journal mode.

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal-sqlite3#47]
Setting the [journal mode](https://sqlite.org/pragma.html#pragma_journal_mode) isn't standardized. 

Suggested url format:
```
DB.open "sqlite3://./data.db?journal_mode=wal"
```

Putting the journal mode in the connection params allows all ORM's to transparently pass through the journal mode.

**Comment by Blacksmoke16** [comment]
Resolved via https://github.com/crystal-lang/crystal-sqlite3/pull/85
