### ISSUE TITLE
Enable foreign key checking.

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal-sqlite3#48]
By default sqlite3 doesn't check foreign keys. For application portability and consistency with other db implmentations it should be enabled.

After reviewing a variety of projects using crystal-sqlite3
* Several of them are amber or other orm's which require mysql/pg/sqlite.  +1 For consistency between databases.
* The remainder don't appear to use foreign keys.  Changing the default is unlikely to affect them.

Not changing the default can also lead to broken behavior.  Applications that depend on `CASCADE` can break when moving between other db engines and sqlite.

**Comment by straight-shoota** [comment]
Foreign keys are a feature of the database implementation. How do you expect this to be addressed in a driver?

**Comment by didactic-drunk** [comment]
This driver is an outlier.  Foreign keys don't work unless specifically enabled.

**Comment by didactic-drunk** [comment]
The driver sending `PRAGMA foreign_keys = 1` on connect will bring it in line with other db implementations and closer to conforming with SQL standards.

**Comment by bcardiff** [comment]
I think people that choose to use sqlite are used to that behavior.
crystal-db connections should be able to exec pragmas.
crystal-db pool have a way to prepare all their connection in a specific way: `Database#setup_connection`.

If this setting is broadly used we could add that in the connection string as a query string. But other than that is part of the setup of the orm or project.

**Comment by didactic-drunk** [comment]
Maybe I phrased the problem incorrectly.

1. Is crystal trying to abstract away platform specifics?  If yes for the filesystem and DB API connections then why not  foreign keys?
2. Users switching from one database to another can be caught off guard by nonfunctional foreign keys.
3. Most users of PostgreSQL and MySQL are suprised that foreign keys need multiple options turned on for foreign keys to work.
4. Should SQL standards be followed univerisally by a universal driver when there is an option to do so?
5. ORM users are even worse off.  They expect the ORM abstracts away the individual SQLism's to provide a uniform interface.  In
6. Should every ORM have to implement the same code over and over?
7. Sqlite3 is an outlier.  No other major database vendor has them off by default.  The behavior is often unwanted and unexpected.  Why would anyone waste their time writing `REFERENCES foo(id)` if it doesn't work?  Based on that alone it's not likely to break any code.

**Comment by didactic-drunk** [comment]
Even if you turned foreign keys on they still wouldn't break most applications.  Sqlite behavior is so outside the norm specifying `REFERENCES foo(id)` does nothing **even with foreign keys enabled**.

Compare [postgres](https://www.postgresql.org/docs/12/ddl-constraints.html#DDL-CONSTRAINTS-FK) and [sqlite](https://sqlite.org/foreignkeys.html) `NO ACTION` (the default).
* Postgres/mysql/etc takes `NO ACTION` to mean the action isn't allowed and returns an error.
* Sqlite takes `NO ACTION` to mean the *constraint* performs no action allowing a silent error which is exactly the opposite of what is intended by anyone specifying a constraint.

**Comment by didactic-drunk** [comment]
> If this setting is broadly used we could add that in the connection string as a query string. But other than that is part of the setup of
> the orm or project.

Which ORM's allow you to set foreign key enforcement for sqlite?  I didn't find any that do.

| ORM        | Option to enable foreign keys          | Notes |
| ------------- |:-------------| -----|
| Crecto      | No |  |
| Clear | |  PostgreSQL only |
| Granite | No |  |
| Jennifer | No |  |
| Onyx/SQL | No |  |
| Topaz |  No   |  |

Should each project maintain it's own code for Sqlite or should there be a standard setting in the driver?  Preferabably with a standardized (on) default so databases can be switched without changes in behavior.

**Comment by didactic-drunk** [comment]
> crystal-db pool have a way to prepare all their connection in a specific way: `Database#setup_connection`.

@bcardiff Jennifer, Granite and I assume most ORM's instantiate the connection on their own.  How and where would I override `setup_connection` when using an ORM? 

If the functionality isn't in the driver I have no other way of accessing it reliably other than digging in to the internals of the ORM.

**Comment by straight-shoota** [comment]
@didactic-drunk It is paramount that a database driver only provides a transparent interface for the database systems. It must not interfere with its implementation.

1. How is handling of foreign keys platform specific in SQLite?
2. Foreign keys being disabled by default is a property of SQLite.
3. ditto
4. The SQL standard does not determine whether foreign key checking is to be enabled by default.
5. The ORM is responsible for mapping database features correctly, not the driver. The driver provides an interface for that, but not all crystal-db drivers can be expected to behave identically. They still interface completely different database systems. You can bring this issue to their attention.
6. Not necessarily but that's for the ORM developers to define.
7. Well, then change this setting in sqlite3 or don't use it.

Please consider the use case where this driver is used for a generic SQL client. Executing arbitrary SQL code with `crystal-sqlite3` should behave exactly the same as with any other SQLite client. This would not be the case if the driver changed any database settings by default.

**Comment by didactic-drunk** [comment]
>     6\. Not necessarily but that's for the ORM developers to define.
> 
>     7\. Well, then change this setting in sqlite3 or don't use it.
> 
> 

How?  No ORM's provide the ability.  Can there be an option in the driver to turn it on so there's not duplicate code in every single application or ORM that wants database portability?

> Please consider the use case where this driver is used for a generic SQL client. Executing arbitrary SQL code with `crystal-sqlite3` should behave exactly the same as with any other SQLite client. This would not be the case if the driver changed any database settings by default.

I'm considering the common cases of:
1. Database portability by changing the connection string (every ORM and some apps).
2. Sqlite clients who don't use foreign keys.  They don't specify them and certainly not with `ON UPDATE` clauses.
3. Developers intending foreign keys to work when they specify them.  Why would they specify them if they don't want them to work?

My sampling of code shows sqlite applications don't use foreign keys.  Nothing breaks by turning it on.  Even if they specify foreign keys **and** foreign keys are on it still doesn't check them unless specific actions are chosen.  

With foreign keys off:
```
# Not checked.
* foo REFERENCES foo(id)

# Not checked.
* foo REFERENCES foo(id) ON UPDATE CASCADE ON DELETE CASCADE
```

With foreign keys on:
```
# Not checked.
* foo REFERENCES foo(id)

# Enforced.
* foo REFERENCES foo(id) ON UPDATE CASCADE ON DELETE CASCADE
```

If they went to the trouble to specify `ON UPDATE` then foreign keys are likely on or their application may not function.  If they didn't specify `ON UPDATE` turning fk's on won't hurt them.

Does anyone have an example of an application that would break?  I can't find any.

**Comment by straight-shoota** [comment]
> Does anyone have an example of an application that would break? I can't find any.

If that is the case, why is it disabled in sqlite3? There surely must be a reason to it.

You should argue with sqlite3 maintainers to change this.
The driver should not apply any different default settings by itself. I don't think there is anything to do here.

**Comment by bcardiff** [comment]
My take is that crystal-db goal is to provide a common api and underlying solutions to problems that appear when dealing with any sql database: iterating result sets, handling connections, handling connection pool, and more.

It is not a goal to provide the means to switch from one db provider to another. For example the SQL dialect differs w.r.t. how params are to be passed `$1` vs `?`.

Some drivers provide additional features (pg notify). I expect crystal-db allow those features to be used but I don't expect to make them in into crystal-db.

If the ORM or a shard wants to allow users to switch the driver easily it will need to only allow features that are available in all of the drivers. And it can totally be done, but needs to handle parsing of sql statements or have a query builder. To do that, if there is a need to setup the connections, the means in crystal-db [are already there](https://github.com/crystal-lang/crystal-sqlite3/issues/48#issuecomment-540749660)
