### ISSUE TITLE
Crash when querying on ARM (Failed to raise an exception: FAILURE)

### ISSUE THREAD

**Issue by hkalexling** [crystal-lang/crystal-sqlite3#54]
- Crystal version: 0.33.0
- LLVM: 8.0.0

Here's a minimal example to reproduce

``` crystal
require "sqlite3"

puts "creating DB"

DB.open "sqlite3://./test.db" do |db|
  db.exec "create table if not exists test (number integer)"
end

puts "DB created. Querying"

DB.open "sqlite3://./test.db" do |db|
  begin
    db.query_one "select * from test where number = 1" do |rs|
      pp rs
    end
  rescue e
    puts e
  end
end
```

Console output when running on an armhf device (tested on a Raspberry Pi 3):

```
creating DB
DB created. Querying
Failed to raise an exception: FAILURE
[0x0] ???
```

The same code works as expected on amd64.

**Comment by straight-shoota** [comment]
This is a compiler issue, not related to crystal-sqlite3. Compiling to arm-linux-musleabihf is currently not supported. You should be able to compile to aarch64 if you can run a 64-bit OS on your rpi.

There's a PR on the compiler repo (crystal-lang/crystal#7859) but it's currently stalled.

**Comment by hkalexling** [comment]
I am running Ubuntu on the RBP and `gcc -dumpmachine` gives `arm-linux-gnueabihf`. According to https://github.com/crystal-lang/crystal/wiki/Platform-Support, it's a tier 2 platform so I expect it to work.

I will try and see if it works on aarch64. Thanks!

**Comment by straight-shoota** [comment]
Okay. Anyways, you should open an issue on the crystal repo, including reproducible steps and system information. For example full output of `crystal version` shows the default target triple - or if you cross-compile, the compiler command you run.
