### ISSUE TITLE
How to use a different version of SQLite?

### ISSUE THREAD

**Issue by samueleaton** [crystal-lang/crystal-sqlite3#57]
If I install a newer version of SQLite (e.g. in `/usr/local/`) how do I get crystal to use the newer binaries?

**Comment by chillfox** [comment]
I am trying to figure this out as well (specifically to use the pre-release version).

**Comment by chillfox** [comment]
ok, I finally figured it out. Please let me know if there is a better way.


Download and build SQLite
(this creates the sqlite command)

```sh
wget https://sqlite.org/snapshot/sqlite-snapshot-202010201440.tar.gz
tar xvfz sqlite-snapshot-202010201440.tar.gz
cd sqlite-snapshot-202010201440
./configure
make
```


Build libsqlite

```sh
gcc -lpthread -ldl -shared -o libsqlite3.so.0 -fPIC sqlite3.c
```


Link crystal program agains specific libsqlite version

```sh
ls libsqlite3.so.0
crystal build --link-flags -L./ --link-flags -lsqlite3 src/db_test.cr
```


Specify library path at runtime

```sh
LD_LIBRARY_PATH=./ ./db_test
```

**Comment by bcardiff** [comment]
pkg-config can be used to instruct crystal where to find the libraries.

Basically crystal does `$ pkg-config --libs sqlite3` to determine de link flags.

If `PKG_CONFIG_PATH` is changed to include some custom locations you can tweak the link flags as pleased

```
$ PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig" pkg-config --libs sqlite3`
-L/usr/local/Cellar/sqlite/3.33.0/lib -lsqlite3
```

So, set up somehow the `PKG_CONFIG_PATH` and compile as usual.

```
$ PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig" crystal build src/db_test.cr
```
