### ISSUE TITLE
REGEXP support

### ISSUE THREAD

**Issue by yujiri8** [crystal-lang/crystal-sqlite3#61]
The [sqlite3 REGEXP operator](https://www.sqlite.org/lang_expr.html#regexp) relies on a user-defined `regexp` function which is not defined by default, so regex support requires specifying a function. Does/will this library have an API to connect Crystal's stdlib regex functionality to it?

**Comment by bcardiff** [comment]
Sounds reasonable to be added. PR are welcome. I think the regex functionality can be added by default, no need for configuration options since the language/std-lib also support regex.
